### ISSUE TITLE
Audio queue overflow! with asterisk integration

### ISSUE THREAD

**Issue by Salmondx** [unispeech/unimrcp#200] opened 2017-06-19 12:40 UTC
We have encountered this issue while trying to call a SynthAndRecog function of a asterisk-unimrcp connector.
```
[2017-06-19 15:32:55] WARNING[7378][C-00000000] audio_queue.c: (ASR-0) Audio queue overflow!
[2017-06-19 15:32:55] ERROR[7378][C-00000000] app_synthandrecog.c: (ASR-0) Recognition terminated prematurely
[2017-06-19 15:32:55] WARNING[7378][C-00000000] app_synthandrecog.c: (ASR-0) Unable to retrieve result
```
Our dial plan is:
```
exten => s,1,Answer
exten => s,n(recog),Verbose(2,!!! Before recognition)

exten => s,n,SynthAndRecog(Hello,/usr/local/unimrcp/data/grammar_ru.xml,p=default&b=0)
exten => s,n,MRCPSynth(Your answer is ${RECOG_RESULT}, p=default)

exten => s,n,Verbose(2,!!! After recognition)
exten => s,n,Verbose(2, ${RECOG_STATUS}, ${RECOG_COMPLETION_CAUSE},${RECOG_RESULT})

;exten => s,n,Hangup
exten => s,n,Goto(recog)
```
TTS functions work as expected, asterisk and unimrcp paired correctly.
Have no idea how to fix that.

**Comment by achaloyan** [comment] 2017-06-19 21:16
It is clear that the recognition did not even start. If you can reproduce the problem with the log level set to DEBUG in mrcp.conf and logger.conf, I may be able to tell you the reason.

**Comment by achaloyan** [comment] 2017-07-12 19:54
I am closing this issue. If you manage to reproduce the problem, please open a new issue under unispeech/asterisk, since this is the right place for Asterisk related issues.

**Closed by achaloyan** 2017-07-12 19:54 UTC
