### ISSUE TITLE
Null MRCPv2 connection  occured  by accident

### ISSUE THREAD

**Issue by wujsy** [unispeech/unimrcp#259] opened 2019-12-20 08:56 UTC
Hi,  in my system, used freeswith+unimrcp framework,  there are about six thousands calls everyday accessed successfully but several calls failed,   in the clinet log file, there are  infos like this: 
"Null MRCPv2 connection <0b9311b2223511ea@speechrecog>"
this question tortures me and I don't know what's the problem,  any ideas? 
I'll appreciate it. 
unimrcp version: 1.6.0

**Comment by achaloyan** [comment] 2019-12-24 22:11
The statement "Null MRCPv2 connection" is logged when the client application attempts to send a new request to the server, but the TCP connection MRCPv2 messages are carried over is no longer available. This issue might be caused by the server untimely closing or dropping the connection.

**Comment by wujsy** [comment] 2019-12-25 05:43
@achaloyan  Thank you for your response, I'll check it

**Comment by lyu0723** [comment] 2020-01-09 03:43
@wujsy 
Hi, I have a same question with you, it was not worked on restarting, could you mind to tell me how to fixed it ?  Thinks a lot.

**Comment by wujsy** [comment] 2020-01-09 06:51
@lyu0723  sorry, I have not solved yet,  and have no idea why server untimely closed the connection

**Comment by coldnight** [comment] 2020-01-19 09:16
@achaloyan Could you please check out this https://github.com/signalwire/freeswitch/issues/196, I may submit that to a wrong palce :).

**Comment by achaloyan** [comment] 2020-03-25 03:05
On one side, the proposed fixed should not harm. However, I do not think the change addresses the root cause. 

The question is how/when connection->sock can be NULL. If you track the client MRCPv2 transport code, you will see that this may happen when the server disconnects. So, it looks like such an event is not properly handled in FS to stop all the activities and release associated resources. 

But this issue requires more thorough analysis and investigation, which I have absolutely no time for.

**Comment by achaloyan** [comment] 2020-03-28 22:13
See comments in [this](16185557194726d35831faf020d1fc92c2703f4a) commit for more info.

**Closed by achaloyan** 2020-03-28 22:13 UTC

**Comment by lewiszlw** [comment] 2022-05-10 07:20
Have you solved this problem? @wujsy

**Comment by coldnight** [comment] 2022-05-10 07:46
@lewiszlw I can't remember very clearly, as it's kinda long time ago. It could be a sign that UniMRCP's queue is full, and connections had been idled very long time. And finally, I deployed a OpenSIPs that balances multiple UniMRCP instances, that may solved this problem.

**Comment by lewiszlw** [comment] 2022-05-10 08:24
Thanks a lot @coldnight . We have plan to integrate opensips as balancer in our systems, but not started. Could you please give your wechat and share you experiences? (You can send to lewiszlw520@gmail.com if you don't mind)

**Comment by michaelplevy** [comment] 2022-05-11 13:52
FYI, this thread led me to https://vipul.xyz/2020/06/mrcp-server-load-balancer.html. Perhaps that will  be helpful.
