### ISSUE TITLE
bag. crash process asterisk

### ISSUE THREAD

**Issue by hamel1on** [unispeech/unimrcp#208] opened 2017-12-19 12:43 UTC
The problem occurs when you use several profiles in /etc/asterisk/mrcp.conf.
If in the settings of the profiles intersect the ports. 
The problem occurs if profiles are used at the same time.
example:
[p1]
rtp-port-min = 4000
rtp-port-max = 4500
[p2]
rtp-port-min = 4000
rtp-port-max = 4500

**Comment by achaloyan** [comment] 2017-12-29 21:53
I agree that RTP port ranges should not intersect. It would make sense to validate the configuration after the initial load to prevent such an configuration error. BTW, can you provide a backtrace or run it under the valgrind to identify the root cause of the crash.

For future reference, please report Astersik related problems to https://github.com/unispeech/asterisk-unimrcp

**Comment by achaloyan** [comment] 2018-04-04 21:49
Closing this issue, since it belongs to the Astreisk app_unimrcp module, and needs to be reported to the corresponding project.

**Closed by achaloyan** 2018-04-04 21:49 UTC
