### ISSUE TITLE
crash process asterisk

### ISSUE THREAD

**Issue by hamel1on** [unispeech/unimrcp#197] opened 2017-05-22 11:13 UTC
The problem is when you turn off MRCPserver during recognition.

Asterisk 13.14.0, UniMRCP modules 1.4.0, os Ubuntu 16.04.2 LTS. 
cat /var/log/kern.log
May 22 12:58:27 speech-ubuntu-16 kernel: [427817.260445] do_general_protection: 9 callbacks suppressed
May 22 12:58:27 speech-ubuntu-16 kernel: [427817.260451] traps: MRCP Client[12184] general protection ip:7f0ae8f2142f sp:7f0adeb18dd8 error:0 in libunimrcpclient.so.0.4.0[7f0ae8ef8000+52000]

cat /var/log/apport.log
ERROR: apport (pid 16841) Mon May 22 12:58:28 2017: called for pid 12154, signal 11, core limit 0
ERROR: apport (pid 16841) Mon May 22 12:58:28 2017: executable: /usr/sbin/asterisk (command line "/usr/sbin/asterisk")
ERROR: apport (pid 16841) Mon May 22 12:58:28 2017: is_closing_session(): no DBUS_SESSION_BUS_ADDRESS in environment
ERROR: apport (pid 16841) Mon May 22 12:58:28 2017: apport: report /var/crash/_usr_sbin_asterisk.0.crash already exists and unseen, doing nothing to avoid disk usage DoS

[_usr_sbin_asterisk.0.crash.zip](https://github.com/unispeech/unimrcp/files/1018563/_usr_sbin_asterisk.0.crash.zip)

**Comment by hamel1on** [comment] 2017-05-22 11:34
mrcp.conf
[general]
default-asr-profile = vn812
default-tts-profile = vn812

[vn812]
server-ip=10.10.10.109
rtp-ip=10.10.10.110
version=1
server-port=8000
resource-location=
speechsynth=tts
speechrecog=asr
rtp-port-min=32768
rtp-port-max=40960
playout-delay = 50
max-playout-delay = 200
ptime = 20
rtcp = 1
rtcp-bye = 2
rtcp-tx-interval = 5000
rtcp-rx-resolution = 1000

**Comment by achaloyan** [comment] 2017-05-22 21:57
Well, if I run apport-unpack on the provided report on my Ubuntu 16.04, the procedure fails. Maybe you can provide a backtrace instead.

Since you mentioned mrcp.conf, I'd assume the app_unimrcp module was used, but which application in particular: MRCPRecog() or SynthAndRecog().

Is this problem one to one reproducible to you. If so, what would be the exact scenario.

Asterisk logs, having DEBUG log level enabled, would help.  If you can provide valgrind output, that would be even better.

**Comment by achaloyan** [comment] 2017-06-01 00:23
I tried to simply kill the MRCP server, while SynthAndRecog() was in-progress, but could not reproduce the problem. Moreover, did the same at various stages of execution (while the prompt was playing, after the prompt completed), observing nothing extraordinary, but the expected session termination on hang-up.

Do you have any modification in the source? Try to provide as detailed information as possible.

**Comment by hamel1on** [comment] 2017-06-01 06:16
If I give access to the server, you can see what's the problem?

**Comment by hamel1on** [comment] 2017-06-01 09:18
Yes, the problem does not always manifest itself. Try about 30 times to perform a number of actions:
asterisk -rx "core restart now"
dial to number
killall /usr/local/Nuance/Speech_Server/server/bin/NSSserver

this command must certainly be performed: core restart now

**Comment by hamel1on** [comment] 2017-06-08 09:39
Hello! Managed to reproduce the problem?

**Comment by achaloyan** [comment] 2017-06-10 01:28
Sorry, this is a time consuming task, I could not find a window to try what you last suggested.

**Comment by hamel1on** [comment] 2017-06-10 10:14
Okay, I'll wait.

**Comment by achaloyan** [comment] 2017-06-20 03:24
This issue should be fixed in https://github.com/unispeech/asterisk-unimrcp/commit/7244b5e7c266ed393e8297a9313fddd323806d4c.

Note: please report Asterisk related issues to [unispeech/asterisk-unimrcp](https://github.com/unispeech/asterisk-unimrcp), since [unispeech/unimrcp](https://github.com/unispeech/unimrcp) is used for the core UniMRCP libraries.

**Closed by achaloyan** 2017-06-20 03:24 UTC
