### ISSUE TITLE
Crash during setup request if engine channel is null

### ISSUE THREAD

**Issue by BurhanEyimaya** [unispeech/unimrcp#193] opened 2017-01-04 11:59 UTC
Hi,

When we make a setup request :

In **mrcp_server_session.c** file **mrcp_server_channel_create** method
at this line
**engine_channel = mrcp_server_engine_channel_create(session,channel,resource_name);**

if **mrcp_server_engine_channel_create** returns null, this results a crash in **mpf_codec_lists_intersect** method.

for(i=0; i<codec_list1->descriptor_arr->nelts; i++) {

at this line error occurs because **codec_list1->descriptor_arr** is null.

We found a solution by checking engine_channel in method **mrcp_server_resource_offer_process**

channel = mrcp_server_channel_create(session,&descriptor->resource_name,count,NULL);
if(!channel || !channel->resource **|| !channel->engine_channel**)
{
	return FALSE;
}

But I want to ask if this is a proper solution?
If not what is the correct solution?

**Comment by achaloyan** [comment] 2017-01-10 04:03
Hi Burhan,

Thanks for the detailed report. The suggested change makes sense to me. I'll try to have a closer look tomorrow.

**Comment by achaloyan** [comment] 2017-01-12 19:28
Hi Burhan,

I tried to reproduce the problem without any lack. What I did is set a limit for max number of concurrent channels, in order the function mrcp_server_engine_channel_create() returns NULL. However, in this case, everything works as intended: codec_list1->descriptor_arr is not null, and the server ultimately responds with RTSP 406 Not Acceptable to the incoming SETUP request.

Could you provide any additional information about the incoming SETUP request or the reason mrcp_server_engine_channel_create() returns NULL in your case.

**Comment by BurhanEyimaya** [comment] 2017-01-16 08:06
Hi Achaloyan,

Our setup request message is :
SETUP rtsp://192.168.1.200:2554/media/speechrecognizer RTSP/1.0
CSeq: 1
Transport: RTP/AVP;unicast;client_port=4000-4001

The reason for mrcp_server_engine_channel_create() to return NULL is we have a limit for concurrent channels. When this limit is reached this error occurs.
For testing you can just return NULL in the  **create_channel** method of the **mrcp_engine_method_vtable_t**

**Comment by achaloyan** [comment] 2017-01-17 20:43
Hi Burhan,

Thanks for your clarification. 

When the max concurrent channel count has been reached, and a new RTSP SETUP request containing **no SDP** is received, the server stack indeed crashes as you mentioned.

I agree with your resolution. If engine_channel cannot be created for one or the other reason, it makes no sense to further process the MRCPv1 session offer.

Fixed in e1d0e468fb3a32af016e1024653a1a94121608f5.

Regards,
Arsen

**Closed by achaloyan** 2017-01-17 20:43 UTC
Labels: bug, Component-Plugin, Component-Server, OpSys-All

**Comment by BurhanEyimaya** [comment] 2017-01-18 12:39
Hi Arsen,

Thanks for your interest and solution.

Regards,
Burhan
